name: Release for DragonflyBSD amd64

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: macos-12
    name: Release for DragonflyBSD
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      id: test
      uses: vmactions/dragonflybsd-vm@v0
      with:
        usesh: false
        mem: 8192
        prepare: |
          pkg update
          pkg upgrade -y
          pkg install -y curl rust pkgconf openssl coreutils p5-Digest-SHA
          rehash

        run: |
          rehash
          ls -lah
          rustc --version
          cargo build --release
          cd target/release
          mv hctl hctl-dragonflybsd-amd64
          shasum -a 256 hctl-dragonflybsd-amd64 > sha256-hctl-dragonflybsd-amd64
          
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/hctl-dragonflybsd-amd64
        asset_name: hctl-dragonflybsd-amd64
        tag: ${{ github.ref }}
    - name: Upload checksum to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/sha256-hctl-dragonflybsd-amd64
        asset_name: sha256-hctl-dragonflybsd-amd64
        tag: ${{ github.ref }}