name: Publish for MacOS X amd64

on:
  push:
    tags:
      - '*'

jobs:
  publish_for_macosx_amd64:
    name: Build for MacOS X amd64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: | 
          cargo build --release
          cd target/release
          mv hctl hctl-macosx-amd64
          /usr/local/bin/gsha256sum hctl-macosx-amd64 > sha256-hctl-macosx-amd64
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/hctl-macosx-amd64
        asset_name: hctl-macosx-amd64
        tag: ${{ github.ref }}
    - name: Upload checksum to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/sha256-hctl-macosx-amd64
        asset_name: sha256-hctl-macosx-amd64
        tag: ${{ github.ref }}